<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC201808011230" name="com.test.git.testNG.TimeOutTest" tests="2" failures="0" timestamp="9 Dec 2019 09:39:18 GMT" time="4.014" errors="1">
  <testcase name="testSuccess" time="2.001" classname="com.test.git.testNG.TimeOutTest"/>
  <testcase name="testFailed" time="2.013" classname="com.test.git.testNG.TimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testFailed() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testFailed() didn't finish within the time-out 2000
]]>
    </error>
  </testcase> <!-- testFailed -->
</testsuite> <!-- com.test.git.testNG.TimeOutTest -->
